#!/usr/bin/env bash
set -euo pipefail

usage() { printf '%s\n' "Usage: ./scripts/setup-mac.sh [--cute|--classic]" "  --cute     Pastel-pink Starship prompt" "  --classic  Powerlevel10k prompt"; }
style=""
case "${1:-}" in
  --cute) style=cute ;;
  --classic) style=classic ;;
  -h|--help) usage; exit 0 ;;
  "") ;;
  *) usage >&2; exit 1 ;;
esac

[[ "$(uname -s)" == "Darwin" ]] || { echo "This script is only for macOS." >&2; exit 1; }
command -v brew >/dev/null 2>&1 || { echo "Install Homebrew first; see docs/MAC_SETUP.md." >&2; exit 1; }
if [[ -z "$style" ]]; then
  read -r -p "Enable the cute pastel-pink prompt? [Y/n] " answer
  case "${answer:-y}" in y|Y|yes|YES) style=cute ;; *) style=classic ;; esac
fi

echo "Installing Mac applications and command-line tools..."
brew install git gh python sqlite
brew install --cask iterm2 font-caskaydia-cove-nerd-font
[[ "$style" != cute ]] || brew install starship

if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  RUNZSH=no CHSH=no KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
zsh_custom="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
clone_if_missing() { [[ -d "$2/.git" ]] || git clone --depth=1 "$1" "$2"; }
clone_if_missing https://github.com/zsh-users/zsh-autosuggestions "$zsh_custom/plugins/zsh-autosuggestions"
clone_if_missing https://github.com/zsh-users/zsh-syntax-highlighting.git "$zsh_custom/plugins/zsh-syntax-highlighting"
if [[ "$style" == classic ]]; then
  clone_if_missing https://github.com/romkatv/powerlevel10k.git "$zsh_custom/themes/powerlevel10k"
fi

config_dir="$HOME/.config/finapp-shell"
config_file="$config_dir/zshrc.zsh"
mkdir -p "$config_dir"
stamp="$(date +%Y%m%d-%H%M%S)"
[[ ! -f "$config_file" ]] || cp "$config_file" "$config_file.backup-$stamp"
[[ ! -f "$HOME/.zshrc" ]] || cp "$HOME/.zshrc" "$HOME/.zshrc.finapp-backup-$stamp"
if [[ "$style" == cute ]]; then
  mkdir -p "$HOME/.config"
  starship preset pastel-powerline -o "$HOME/.config/starship.toml"
  pre_theme='ZSH_THEME=""'
  post_theme='eval "$(starship init zsh)"'
else
  pre_theme='ZSH_THEME="powerlevel10k/powerlevel10k"'
  post_theme='[[ ! -f "$HOME/.p10k.zsh" ]] || source "$HOME/.p10k.zsh"'
fi
{
  printf '%s\n' "# Generated by Finapp's macOS bootstrap." 'export ZSH="$HOME/.oh-my-zsh"' "$pre_theme" \
    'plugins=(git zsh-autosuggestions zsh-syntax-highlighting)' "zstyle ':omz:update' mode reminder" \
    'source "$ZSH/oh-my-zsh.sh"' "$post_theme" '' 'ZSH_AUTOSUGGEST_STRATEGY=(history completion)' \
    'ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"' 'HISTSIZE=50000' 'SAVEHIST=50000' \
    'setopt HIST_IGNORE_ALL_DUPS SHARE_HISTORY HIST_REDUCE_BLANKS' \
    'export PATH="$HOME/.local/bin:$HOME/bin:$PATH"'
} > "$config_file"
source_line='[[ ! -f "$HOME/.config/finapp-shell/zshrc.zsh" ]] || source "$HOME/.config/finapp-shell/zshrc.zsh"'
touch "$HOME/.zshrc"
grep -Fq 'finapp-shell/zshrc.zsh' "$HOME/.zshrc" || printf '\n# Finapp-managed friendly shell setup\n%s\n' "$source_line" >> "$HOME/.zshrc"

if ! gh auth status >/dev/null 2>&1; then
  echo "GitHub login is required for her private database repository."
  gh auth login
fi
printf '\n%s\n' "Mac setup complete." "Select CaskaydiaCove Nerd Font in iTerm2 > Settings > Profiles > Text."
[[ "$style" != classic ]] || echo "Open a new iTerm2 window and run: p10k configure"
echo "Then return here and run: ./run.sh"
